---
title: "Build BCR Databases"
vignette: >
  %\VignetteIndexEntry{Build OmniPathR databases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author: "`r 'Author: Matthew Hung'`"
date: "`r paste('Last Updated:', format(Sys.Date(), '%Y/%m/%d'))`"
output:
  html_document:
    code_folding: hide
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---
```{r}
library(tidyverse)
library(readxl)
```

## SarsCoV2 S2
```{r}
s2pos <- list()
````

### CoV-AbDab
```{r}
covabdab_2024 <- read.csv("./resource/CoV-AbDab_2024.csv")
covabdab_2024 %>% head() %>% show()
```

```{r}
covabdab_2024 <- covabdab_2024 %>%
  filter(str_detect(Origin, "[Hh]uman")|str_detect(Origin, "[Mm]ouse")) %>%
  filter(str_detect(`Protein...Epitope`, "S2")) %>%
  mutate(
    ref_antigen = "SarsCoV2",
    ref_strain = `Binds.to`,
    ref_epitope = "S2",
    ref_binding = TRUE,
    ref_org = ifelse(str_detect(Origin, "[Hh]uman"), "human", "mouse"),
    ref_publication = "CoV-AbDab_2024",
    ref_name = Name,
    ref_heavyV = gsub(" .*", "", `Heavy.V.Gene`),
    ref_heavyJ = gsub(" .*", "", `Heavy.J.Gene`),
    ref_heavyCDR3 = paste0("C", `CDRH3`, "W"),
    ref_lightV = gsub(" .*", "", `Light.V.Gene`),
    ref_lightJ = gsub(" .*", "", `Light.J.Gene`),
    ref_lightCDR3 = paste0("C", `CDRL3`, "W")
  ) %>%
  dplyr::select(ref_antigen, ref_strain, ref_epitope, ref_binding, ref_org, ref_publication, ref_name, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(covabdab_2024)

s2pos[[1]] <- covabdab_2024
```

### LopezDeAssis_2023
```{r}
lopezdeassiz_2023 <- read.csv("./resource/LopezDeAssis_2023.csv")
lopezdeassiz_2023 %>% head() %>% show()
```

```{r}
lopezdeassiz_2023 <- lopezdeassiz_2023 %>%
  filter(str_detect(.[[1]], "^Spike")) %>%
  mutate(
    ref_antigen = "SarsCoV2",
    ref_strain = "mRNA-1273",
    ref_epitope = "S2",
    ref_binding = TRUE,
    ref_org = "human",
    ref_publication = "LopezDeAssis_2023",
    ref_name = `X`,
    ref_heavyV = v_call_VDJ_main,
    ref_heavyJ = j_call_VDJ_main,
    ref_heavyCDR3 = junction_aa_VDJ,
    ref_lightV = v_call_VJ_main,
    ref_lightJ = j_call_VJ_main,
    ref_lightCDR3 = junction_aa_VJ
  ) %>%
  dplyr::select(ref_antigen, ref_strain, ref_epitope, ref_binding, ref_org, ref_publication, ref_name, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(lopezdeassiz_2023)

s2pos[[2]] <- lopezdeassiz_2023
```

```{r}
s2pos <- bind_rows(s2pos)
write.csv(s2pos, "./inst/extdata/SarsCoV2_S2+.csv", row.names = FALSE)
```


## Vaccinia
```{r}
b5pos <- list()
```

### Chappert_2022 IGH only
```{r}
chappert_2022_1 <- read_excel("./resource/Chappert_2022.xlsx", sheet = 3, skip = 2)
chappert_2022_1 %>% head() %>% show()
```

```{r}
chappert_2022_1 <- chappert_2022_1 %>%
  mutate(
    ref_antigen = "Vaccinia",
    ref_strain = NA,
    ref_epitope = "B5",
    ref_binding = TRUE,
    ref_org = "human",
    ref_publication = "Chappert_2022",
    ref_name = sequence_id,
    ref_heavyV = gsub("\\*.*", "", v_call),
    ref_heavyJ = gsub("\\*.*", "", j_call),
    ref_heavyCDR3 = cdr3,
    ref_lightV = NA,
    ref_lightJ = NA,
    ref_lightCDR3 = NA
  ) %>%
  dplyr::select(ref_antigen, ref_strain, ref_epitope, ref_binding, ref_org, ref_publication, ref_name, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(chappert_2022_1)

b5pos[[1]] <- chappert_2022_1
```

```{r}
chappert_2022_2 <- read_excel("./resource/Chappert_2022.xlsx", sheet = 4, skip = 3)
chappert_2022_2 %>% head() %>% show()
```

```{r}
chappert_2022_2 <- chappert_2022_2 %>%
  mutate(
    ref_antigen = "Vaccinia",
    ref_strain = NA,
    ref_epitope = "B5",
    ref_binding = TRUE,
    ref_org = "human",
    ref_publication = "Chappert_2022",
    ref_name = cell_id,
    ref_heavyV = gsub("\\*.*", "", `v_call...8`),
    ref_heavyJ = gsub("\\*.*", "", `j_call...10`),
    ref_heavyCDR3 = `cdr3...11`,
    ref_lightV = gsub("\\*.*", "", `v_call...16`),
    ref_lightJ = gsub("\\*.*", "", `j_call...17`),
    ref_lightCDR3 = `cdr3...18`
  ) %>%
  dplyr::select(ref_antigen, ref_strain, ref_epitope, ref_binding, ref_org, ref_publication, ref_name, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(chappert_2022_2)

b5pos[[2]] <- chappert_2022_2
```


```{r}
b5pos <- bind_rows(b5pos)
write.csv(b5pos, "./inst/extdata/Vaccinia_B5+.csv", row.names = FALSE)
```